### ISSUE TITLE
请求数据联动

### ISSUE THREAD

**Issue by psychopasss** [coding-fox/apidoc-plugin-websocket#2]
![image](https://user-images.githubusercontent.com/11738089/43175398-581d0a24-8ff1-11e8-8681-310cf9fe56c6.png)
如图，希望填写参数，自动生成  下面提交的message

**Comment by yanzhenyu** [comment]
![image](https://user-images.githubusercontent.com/11738089/43175398-581d0a24-8ff1-11e8-8681-310cf9fe56c6.png)
如图，希望填写参数，自动生成  下面提交的message
